### ISSUE TITLE
Improve rules/mocha by adding specific globals

### ISSUE THREAD

**Issue by rewop** [Konnektid/eslint-config-konnektid#16]
We could improve the [mocha rule](https://github.com/Konnektid/eslint-config-konnektid/blob/master/rules/mocha.js) by adding specific globals needed for mocha:

```json
globals: {
    "describe": false,
    "it": false,
    "before": false,
    "after": false,
    "beforeEach": false,
    "afterEach": false
}
```

**Comment by Lapixx** [comment]
The `env` takes care of these global variables already, no need to manually define them.

If you receive errors from the `no-undef` rule, make sure you've set your config to extend from `konnektid/test` correctly.

**Comment by rewop** [comment]
I see then we can close this one.
