### ISSUE TITLE
Invert react/jsx-boolean-value

### ISSUE THREAD

**Issue by rewop** [Konnektid/eslint-config-konnektid#19]
At the moment the the [rule is is set to show error if no boolean value is passed to a flag property](https://github.com/Konnektid/eslint-config-konnektid/blob/master/rules/jsx.js#L21). However, flag (boolean) property, in jsx read better without value:

```jsx
// now
<button primary={true}>Next</button>

// after
<button primary>Next</button>
```

The second case reads much better. 

[Here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) how to configure the rule. It is as simple as changing the argument `always` to `never` so the first case would show an error.

**Comment by Lapixx** [comment]
Good catch, this was intended to warn about `flag={true}` cases indeed, but must have misconfigured it.
