### ISSUE TITLE
Use babel-eslint

### ISSUE THREAD

**Issue by Lapixx** [Konnektid/eslint-config-konnektid#22]
And preferably find a way to manage all peerDependencies.

**Comment by rewop** [comment]
I am using it myself and is working fine so far. @Lapixx  Can you elaborate more on the problem of the peerDependencies?

**Comment by Lapixx** [comment]
Having to manually install it as a peerDependency is pretty annoying (and basically this module doesn't properly work stand-alone). There's an issue open for this at ESLint: eslint/eslint#3458

Either way, having the parser in place just makes sure that ESLint doesn't break on the code. Actually linting the ES6/7 features wouldn't work out of the box, and requires additional plugins (think [babel/eslint-plugin-babel](/babel/eslint-plugin-babel)). Something to look into later maybe, but still keep this in mind.

I'll try to add this in #20 and merge soon.
