### ISSUE TITLE
Disable global-require for frontend config

### ISSUE THREAD

**Issue by Lapixx** [Konnektid/eslint-config-konnektid#5]
We should disable the `global-require` for the `frontend` configuration as it is best practice in React to require local styles in the render function:

```js
class MyComponent extends Component {
    render() {
         const styles = require("./MyComponent.scss");
         ....
    }
}
```

**Comment by rewop** [comment]
Another use case is for frontend code that gets bundle. You may want to include in the bundle code only in development. To do so in webpack you can define a global `__DEVELOPMENT__`, and then require your development tools in the following way:

```
if (__DEVELOPMENT_) {
  require('./my-dev-toolkit');
  ...
}
```
