### ISSUE TITLE
Update eslint peerDependency to version 2

### ISSUE THREAD

**Issue by rewop** [Konnektid/eslint-config-konnektid#6]
At the moment it is at version 1.0.0 and, usually in our software we have installed version 2 needed by other peerDependencies

**Comment by Lapixx** [comment]
Our main packages still use ESLint `1.9.0` or `1.10.0` for linting our own codebase. Apart from changing the peerDependency version, this will also require some changes in the configuration files. Opened #7.

**Comment by rewop** [comment]
Yes indeed. I made a quick test, and the eslint failed with jsx file at least. 
We should update to avoid to fall too behind.

**Comment by rewop** [comment]
Let's continue discussion in #7
